# an_assertion_error.py
assert(1 == 1)  # this will pass
